export const products = [ 
  {
    id: 1,
    slug: "air-zoom-pro-runners",
    name: "Air-Zoom Pro Runners",
    category: "Fashion",
    price: 145.0,
    originalPrice: 180.0,
    rating: 4.7,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"
    ],
    badge: null,
    description: "Premium running shoes designed for speed and elite comfort.",
    soldBy: "Urban Threads",
    features: [
      "Responsive Zoom cushioning",
      "Breathable engineered mesh",
      "Lightweight build for long runs"
    ],
    specifications: {
      weight: "220g (per shoe)",
      materials: "Engineered mesh, foam midsole, rubber outsole",
      sizes: "US 6 - 13",
      care: "Machine wash cold, air dry"
    },
    reviewsSummary: {
      average: 4.7,
      count: 712,
      breakdown: {5: 68,4:20,3:8,2:2,1:2}
    },
    relatedProductIds: [2,9,15]
  },
  {
    id: 2,
    slug: "gold-rimmed-aviators",
    name: "Gold-Rimmed Aviators",
    category: "Fashion",
    price: 210.0,
    originalPrice: null,
    rating: 4.5,
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=1200&q=80"
    ],
    badge: "New Arrival",
    description: "Designer aviator sunglasses with polarized gold-tinted lenses.",
    soldBy: "Urban Threads",
    features: [
      "Polarized lenses",
      "Gold metal frame",
      "UV400 protection"
    ],
    specifications: {
      frame: "Gold-plated alloy",
      lens: "Polarized TAC",
      width: "58mm",
      case: "Hard protective case included"
    },
    reviewsSummary: { average: 4.5, count: 234 },
    relatedProductIds: [1,9]
  },
  {
    id: 3,
    slug: "elysium-cologne",
    name: "Elysium Cologne",
    category: "Beauty",
    price: 125.0,
    originalPrice: 160.0,
    rating: 4.8,
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=1200&q=80"],
    badge: null,
    description: "Luxury men's fragrance with notes of vetiver and amber.",
    soldBy: "Green Life Home",
    features: ["Long-lasting projection","Natural essential blends","Elegant glass bottle"],
    specifications: {
      size: "100ml",
      concentration: "Eau de Parfum",
      notes: "Top: bergamot; Heart: vetiver; Base: amber"
    },
    reviewsSummary: { average: 4.8, count: 421 },
    relatedProductIds: [12]
  },
  {
    id: 4,
    slug: "eco-stream-32oz-bottle",
    name: "Eco-Stream 32oz Bottle",
    category: "Home & Garden",
    price: 34.99,
    originalPrice: null,
    rating: 5.0,
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=1200&q=80"],
    badge: "Eco Friendly",
    description: "Sustainable stainless steel water bottle with double-wall insulation.",
    soldBy: "Green Life Home",
    features: ["Double-wall vacuum insulation","BPA-free cap","Keeps drinks cold for 24 hours"],
    specifications: { capacity: "32oz", material: "18/8 stainless steel", weight: "410g", dimensions: "9.5 x 3.2 in" },
    reviewsSummary: { average: 5.0, count: 1890 },
    relatedProductIds: []
  },
  {
    id: 5,
    slug: "smart-home-camera",
    name: "Smart Home Camera",
    category: "Electronics",
    price: 129.0,
    originalPrice: 159.0,
    rating: 4.9,
    images: ["https://images.unsplash.com/photo-1558002038-1055907df827?w=1200&q=80"],
    badge: null,
    description: "Ultra HD resolution with 360-degree night vision.",
    soldBy: "Tech Haven",
    features: ["4K Ultra HD","360° pan & tilt","Night vision & motion alerts"],
    specifications: { resolution: "4K", connectivity: "Wi-Fi 2.4/5GHz", power: "USB-C 5V", storage: "Cloud & microSD" },
    reviewsSummary: { average: 4.9, count: 1023 },
    relatedProductIds: [8,11,10]
  },
  {
    id: 6,
    slug: "precision-gaming-mouse",
    name: "Precision Gaming Mouse",
    category: "Electronics",
    price: 75.0,
    originalPrice: null,
    rating: 5.0,
    images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?w=1200&q=80"],
    badge: "New",
    description: "High-precision sensor with customizable RGB.",
    soldBy: "Tech Haven",
    features: ["High DPI optical sensor","Customizable RGB","Ergonomic shape"],
    specifications: { dpi: "100 - 16000", connectivity: "Wired USB", weight: "85g (adjustable)", switches: "Omron" },
    reviewsSummary: { average: 5.0, count: 548 },
    relatedProductIds: [19,20]
  },
  {
    id: 7,
    slug: "ultrabook-pro-14",
    name: "UltraBook Pro 14\"",
    category: "Electronics",
    price: 1199.0,
    originalPrice: 1499.0,
    rating: 4.9,
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200&q=80"],
    badge: null,
    description: "Advanced processor with 16GB RAM for pro tasks.",
    soldBy: "Tech Haven",
    features: ["16GB RAM","M-series / Intel i7 options","Lightweight aluminum chassis"],
    specifications: { cpu: "Intel i7 / Apple M-series options", ram: "16GB", storage: "512GB - 2TB SSD", display: "14-inch Retina / IPS" },
    reviewsSummary: { average: 4.9, count: 312 },
    relatedProductIds: [11,8]
  },
  {
    id: 8,
    slug: "premium-soundbar",
    name: "Premium Soundbar",
    category: "Electronics",
    price: 399.0,
    originalPrice: 499.0,
    rating: 4.8,
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1200&q=80"],
    badge: null,
    description: "High-fidelity sound with wireless connectivity.",
    soldBy: "Tech Haven",
    features: ["Dolby Atmos support","Wireless subwoofer","Bluetooth & HDMI eARC"],
    specifications: { channels: "3.1 / 5.1 passthrough", power: "240W total", connectivity: "HDMI eARC, Bluetooth, Optical" },
    reviewsSummary: { average: 4.8, count: 654 },
    relatedProductIds: [5,7]
  },
  {
    id: 9,
    slug: "digital-watch-z1",
    name: "Digital Watch Z1",
    category: "Accessories",
    price: 129.0,
    originalPrice: null,
    rating: 4.5,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200&q=80"],
    badge: null,
    description: "Smart digital watch with fitness tracking.",
    soldBy: "Urban Threads",
    features: ["Heart rate monitor","Sleep tracking","Water resistant 5ATM"],
    specifications: { battery: "7 days typical", connectivity: "Bluetooth 5.0", display: "AMOLED 1.4-inch" },
    reviewsSummary: { average: 4.5, count: 403 },
    relatedProductIds: [10,6]
  },
  {
    id: 10,
    slug: "smart-fitness-band",
    name: "Smart Fitness Band",
    category: "Electronics",
    price: 59.0,
    originalPrice: 79.0,
    rating: 4.9,
    images: ["https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=1200&q=80"],
    badge: null,
    description: "Track your health and fitness goals.",
    soldBy: "Tech Haven",
    features: ["24/7 heart rate","Activity & workout modes","Long battery life"],
    specifications: { battery: "14 days", waterResistance: "5ATM", sensors: "PPG heart rate, accelerometer" },
    reviewsSummary: { average: 4.9, count: 2100 },
    relatedProductIds: [9]
  },
  {
    id: 11,
    slug: "studio-headphones",
    name: "Studio Headphones",
    category: "Electronics",
    price: 280.0,
    originalPrice: null,
    rating: 4.7,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=80"],
    badge: null,
    description: "Professional audio quality for music lovers.",
    soldBy: "Tech Haven",
    features: ["Flat studio response","Comfort-fit ear pads","Detachable cable"],
    specifications: { impedance: "32Ω", frequencyResponse: "10Hz - 30kHz", weight: "310g" },
    reviewsSummary: { average: 4.7, count: 812 },
    relatedProductIds: [7,8]
  },
  {
    id: 12,
    slug: "radiance-serum",
    name: "Radiance Serum",
    category: "Beauty",
    price: 45.0,
    originalPrice: 60.0,
    rating: 4.6,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=1200&q=80"],
    badge: null,
    description: "Nourishing serum for glowing skin.",
    soldBy: "Green Life Home",
    features: ["Vitamin C blend","Lightweight absorbent formula","Cruelty-free"],
    specifications: { size: "30ml", skinType: "All", activeIngredients: ["Vitamin C","Hyaluronic Acid"] },
    reviewsSummary: { average: 4.6, count: 142 },
    relatedProductIds: [3]
  },
  {
    id: 13,
    slug: "keychron-k2-wireless-mechanical-keyboard",
    name: "Keychron K2 Wireless Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    originalPrice: 105.0,
    rating: 4.5,
    images: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCtnbPza9QW06rgBfgjPqUUAFOObaWYJDsSZ1yca_DuvdRQNfpZiDIwDlez-H-y_-m0iQXnwEw57VdiP24nQiFScOQPuepXgoUd6kcosDHe1d90hk4jDf0AevWrpdBBoq6CRWmRKqyl4voQe_jXTmD8HDZHdjj7r5oXh0sHZ9dwTSiQ9h-KKTotW38_jmh9pQnFaY4aDxNEa_3bdfq4OvkpfF2P-y6W8aP-D46oSe6HnTR33TSDdiCwfCln7JFkrfZvq2c2rGpw0ew"
    ],
    badge: "-15%",
    description: "Wireless mechanical keyboard with RGB lighting and compact layout.",
    soldBy: "Tech Haven",
    features: ["Bluetooth wireless","Hot-swappable options","RGB backlight"],
    specifications: { layout: "75% / Compact", switches: "Gateron / Keychron options", battery: "2000mAh", connectivity: "Bluetooth / USB-C" },
    reviewsSummary: { average: 4.5, count: 980 },
    relatedProductIds: [14,16,15]
  },
  {
    id: 14,
    slug: "logitech-mx-mechanical-mini-for-mac",
    name: "Logitech MX Mechanical Mini for Mac",
    category: "Electronics",
    price: 149.99,
    originalPrice: null,
    rating: 4.0,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuC_jeGOmRc4axL89RHDzqlzAlvFA-FzxgdTs7daBbgClKYgp8SRoJ6Ytz5m0wR45kd8lCmihnx1Oj0S_mk9svvht-3rLtqvu1CjghEFXQ84zN5hwjgPSbWJ7DBkqUnaLWkdxdJpBF-PRcqlbDFDTc5kRs6AHuxMP2SZCkrmLO97eVjAxlTSiyMneGzJqUQZN17p8m_J-A0-jSgj5tH4ZV4NQZ_BqsP7n4UdEu93LGZ4qFJ2g-sd-CWQ9zAPI0y50bAf-8MVDK8mHow"],
    badge: "New",
    description: "Compact low-profile mechanical keyboard tailored for Mac workflows.",
    soldBy: "Tech Haven",
    features: ["Mac layout","Low-profile mechanical switches","Multi-device pairing"],
    specifications: { layout: "65% / Compact", switches: "Low-profile mechanical", connectivity: "Bluetooth / USB-C", battery: "4500mAh" },
    reviewsSummary: { average: 4.0, count: 210 },
    relatedProductIds: [13]
  },
  {
    id: 15,
    slug: "custom-artisan-purple-keycap-set",
    name: "Custom Artisan Purple Keycap Set (Keycaps Only)",
    category: "Accessories",
    price: 45.0,
    originalPrice: null,
    rating: 5.0,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuBpHB1DKm4EQe1UlHCP7MtFsDEfnzo2xfmRNiYtJBHLAPx8ZDUjsUgiYhrJeGTH7tzU5yUCjPg6F2Lj1BCCgYeG1cYme00TwCZ0qtbfOSy-wgiWkhlD0ChTPIet-hBOSCCVznuzFpPQA4RUMITrn5ms9o-Z4B7SnTV6Hzt8t4mRS1iYC2ON2Eyxz3pw4lNkER9jzqXrUU950Ea_BEmEFGWqJBh-gxsioGn8qeRo-uDpr5i9oy8QITLkj38FqSQRQgbay9KvfaHxOaY"],
    badge: null,
    description: "Artisan purple keycap set for custom mechanical keyboards.",
    soldBy: "Urban Threads",
    features: ["Hand-painted artisan keycaps","High-profile sculpted set","Durable PBT material"],
    specifications: { material: "PBT", profile: "SA / Cherry variants", compatibility: "Most MX-style stems" },
    reviewsSummary: { average: 5.0, count: 87 },
    relatedProductIds: [13,16]
  },
  {
    id: 16,
    slug: "8bitdo-retro-mechanical-keyboard-n-edition",
    name: "8BitDo Retro Mechanical Keyboard - N Edition",
    category: "Electronics",
    price: 99.99,
    originalPrice: null,
    rating: 4.5,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuAr82UC0H8WtuxuzQcN2Pp15jnEYUW2_VEsGjgzUgw_6miJPpeGK_tr8hxJwg56k8Bp55LPiNrY0ZoeVeQQyrHAcYBMmzxiwbeeZLHs-ubHsIAn-7Akee4Vc1hsUfjClSUBthmkbF0xcPL5yXtt2dwA4NF-6spDLtMuIGIRrQpK_U2_5qfyOgcQ93_8_ea8mkv9SHfSa8ypWju1lkvSVMQBeiLycV9giiYak-KFi6ZggMb4y7zkpBbg2Q1X19U8l1IjIxHbSr-Jt_I"],
    badge: "Best Seller",
    description: "Retro-inspired mechanical keyboard with modern wireless support.",
    soldBy: "Tech Haven",
    features: ["Bluetooth & 2.4GHz","Retro styling","Hotkey macros"],
    specifications: { layout: "Full / Tenkeyless options", connectivity: "Bluetooth / 2.4GHz / USB-C", battery: "1500mAh" },
    reviewsSummary: { average: 4.5, count: 640 },
    relatedProductIds: [13,15]
  },
  {
    id: 17,
    slug: "corsair-k70-rgb-mk2",
    name: "Corsair K70 RGB MK.2 Mechanical Gaming Keyboard",
    category: "Electronics",
    price: 159.99,
    originalPrice: null,
    rating: 5.0,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuAP-xOp_KCexAGqVfoO6T2qVSa_bUYHDVGYOuSFm2yb0Qn2THawTb4z2sJMjSuDSGESEra5mEStbuxp5VTsjVz-CH3m_rAforqdL42YqKd9I3TFC1NPPa9inOdqFiLptGVu1qoLAf4JYm8mdu2xCoT-DjqLwPeie1_F_PG28YAWfSQMvWFTsdKB95vEgRjr0LxMG4CXox6bwmyR23aPpxEQDLD_Ad9NxdzTQ4oU-BxEkHOk_s8AuAyxYHjvLP0f2JE5Waul2TpIM8c"],
    badge: null,
    description: "Full-size mechanical gaming keyboard with RGB lighting.",
    soldBy: "Tech Haven",
    features: ["Aircraft-grade aluminum frame","Per-key RGB lighting","Dedicated media controls"],
    specifications: { switches: "Cherry MX (varies)", keyRollover: "N-key", connectivity: "Wired USB", weight: "1.2kg" },
    reviewsSummary: { average: 5.0, count: 1540 },
    relatedProductIds: [13,16]
  },
  {
    id: 18,
    slug: "anne-pro-2-mechanical-keyboard",
    name: "Anne Pro 2 Mechanical Keyboard Wireless Bluetooth",
    category: "Electronics",
    price: 65.0,
    originalPrice: 89.0,
    rating: 4.0,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuAo70EnPreGWczd2pumJl-sWCN718BotA55bJqrHop5SIOoje4O_lYmF7AmxeSLw-VraqgONDz6xc_VouMjhfkHTdyRZ92--XH-vUpRPhC4IQMeyQka526plvOeJsPlT3pkOR5IqF_XHgajHMD6HuDM86DblLFvyaVxuevrxzZh4jJlSsXmfSGEh027JyV0nfAsuhW5TwtVUEMCjEgu7AVxI1PnwYOgw16mMk71q4Tel_NDll5CENnHH1x47VngBB2uBiZ4jDGXbWM"],
    badge: "Refurbished",
    description: "Compact 60% wireless mechanical keyboard with Bluetooth.",
    soldBy: "TechRefurb",
    features: ["60% layout","RGB lighting","Bluetooth & wired modes"],
    specifications: { layout: "60%", battery: "2000mAh", switches: "Gateron / Kailh" },
    reviewsSummary: { average: 4.0, count: 320 },
    relatedProductIds: [13,16]
  },
  {
    id: 19,
    slug: "glorious-model-o-wireless-gaming-mouse",
    name: "Glorious Model O Wireless Gaming Mouse",
    category: "Electronics",
    price: 79.99,
    originalPrice: null,
    rating: 4.5,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuABQcTwQDhtR86xNbH2y27HUu5STKat1JdKaPtEFDjzAL6iJmjYBftEWdB6Ado1mQ-Bm0k7OMxI4oleqgl14zOilA4sKJl-DvFi_dU_AKjEQJvXFNaRcObOt9ZrYpOHyTGX15broD3iBhcCnr9lJvUbTFGpW9aRHHB1qk_JsSPbmvSFmBTsvdJQBRVKVkkq7FwZeOoghNhTIWi0dT3WIBJskJhLYJ0bkILPRLXmeIkZ54Ynl3eJLa1ydiYW06iurrFGPEUk45Ilhys"],
    badge: null,
    description: "Ultra-lightweight wireless gaming mouse with honeycomb design.",
    soldBy: "Glorious",
    features: ["Ultra-light honeycomb shell","High-precision sensor","Low-latency wireless"],
    specifications: { weight: "69g", sensor: "Pixart 3370", connectivity: "2.4GHz wireless / USB-C" },
    reviewsSummary: { average: 4.5, count: 980 },
    relatedProductIds: [6,20]
  },
  {
    id: 20,
    slug: "pro-gamer-starter-pack",
    name: "Pro Gamer Starter Pack: Keyboard + Mouse + Mat",
    category: "Electronics",
    price: 120.0,
    originalPrice: 150.0,
    rating: 4.0,
    images: ["https://lh3.googleusercontent.com/aida-public/AB6AXuCoBbO2SQlb1BWmZ3gcAkKme2I83wt7D8_cGd1x7k6j50Mh-CLmy3o_Znkb-Y0lGSpoD-KHwbH4VUH5yzqrupbF1kaicbey197uLg-1ZcTw2wTd-WhM_WgXZkIB1B5mchJuOQPQFW53-ZruPTaGgWPWrilC0jCaXaf2ntQCaK8iX_HiswFRkcQw4rsG3hlvcst9kCbc-SzPjuFPKx_1BPG7ZZdIAtzHg2wAIhgltLu3tzZYrW6n-M7orWP9pqckj13ts6RqpbpZRRY"],
    badge: "Bundle",
    description: "Starter bundle with keyboard, mouse, and desk mat.",
    soldBy: "GamerGear",
    features: ["Value bundle","Pre-tuned for esports","Durable stitched mat"],
    specifications: { keyboard: "Membrane / RGB", mouse: "Optical 8000 DPI", mat: "Stitched edges, 900x400mm" },
    reviewsSummary: { average: 4.0, count: 430 },
    relatedProductIds: [6,19]
  }
];

export const productsList = [
  {
    id: 1,
    name: "Air-Zoom Pro Runners",
    category: "Fashion",
    price: 145.00,
    originalPrice: 180.00,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    badge: null,
    description: "Premium running shoes designed for speed and elite comfort.",
    soldBy: "Urban Threads"
  },
  {
    id: 2,
    name: "Gold-Rimmed Aviators",
    category: "Fashion",
    price: 210.00,
    originalPrice: null,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    badge: "New Arrival",
    description: "Designer aviator sunglasses with polarized gold-tinted lenses.",
    soldBy: "Urban Threads"
  },
  {
    id: 3,
    name: "Elysium Cologne",
    category: "Beauty",
    price: 125.00,
    originalPrice: 160.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80",
    badge: null,
    description: "Luxury men's fragrance with notes of vetiver and amber.",
    soldBy: "Green Life Home"
  },
  {
    id: 4,
    name: "Eco-Stream 32oz Bottle",
    category: "Home & Garden",
    price: 34.99,
    originalPrice: null,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    badge: "Eco Friendly",
    description: "Sustainable stainless steel water bottle with double-wall insulation.",
    soldBy: "Green Life Home"
  },
  {
    id: 5,
    name: "Smart Home Camera",
    category: "Electronics",
    price: 129.00,
    originalPrice: 159.00,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80",
    badge: null,
    description: "Ultra HD resolution with 360-degree night vision.",
    soldBy: "Tech Haven"
  },
  {
    id: 6,
    name: "Precision Gaming Mouse",
    category: "Electronics",
    price: 75.00,
    originalPrice: null,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80",
    badge: "New",
    description: "High-precision sensor with customizable RGB.",
    soldBy: "Tech Haven"
  },
  {
    id: 7,
    name: "UltraBook Pro 14\"",
    category: "Electronics",
    price: 1199.00,
    originalPrice: 1499.00,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    badge: null,
    description: "Advanced processor with 16GB RAM for pro tasks.",
    soldBy: "Tech Haven"
  },
  {
    id: 8,
    name: "Premium Soundbar",
    category: "Electronics",
    price: 399.00,
    originalPrice: 499.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80",
    badge: null,
    description: "High-fidelity sound with wireless connectivity.",
    soldBy: "Tech Haven"
  },
  {
    id: 9,
    name: "Digital Watch Z1",
    category: "Accessories",
    price: 129.00,
    originalPrice: null,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    badge: null,
    description: "Smart digital watch with fitness tracking.",
    soldBy: "Urban Threads"
  },
  {
    id: 10,
    name: "Smart Fitness Band",
    category: "Electronics",
    price: 59.00,
    originalPrice: 79.00,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    badge: null,
    description: "Track your health and fitness goals.",
    soldBy: "Tech Haven"
  },
  {
    id: 11,
    name: "Studio Headphones",
    category: "Electronics",
    price: 280.00,
    originalPrice: null,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    badge: null,
    description: "Professional audio quality for music lovers.",
    soldBy: "Tech Haven"
  },
  {
    id: 12,
    name: "Radiance Serum",
    category: "Beauty",
    price: 45.00,
    originalPrice: 60.00,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
    badge: null,
    description: "Nourishing serum for glowing skin.",
    soldBy: "Green Life Home"
  },
  {
    id: 13,
    name: "Keychron K2 Wireless Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    originalPrice: 105.00,
    rating: 4.5,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCtnbPza9QW06rgBfgjPqUUAFOObaWYJDsSZ1yca_DuvdRQNfpZiDIwDlez-H-y_-m0iQXnwEw57VdiP24nQiFScOQPuepXgoUd6kcosDHe1d90hk4jDf0AevWrpdBBoq6CRWmRKqyl4voQe_jXTmD8HDZHdjj7r5oXh0sHZ9dwTSiQ9h-KKTotW38_jmh9pQnFaY4aDxNEa_3bdfq4OvkpfF2P-y6W8aP-D46oSe6HnTR33TSDdiCwfCln7JFkrfZvq2c2rGpw0ew",
    badge: "-15%",
    description: "Wireless mechanical keyboard with RGB lighting and compact layout.",
    soldBy: "Tech Haven"
  },
  {
    id: 14,
    name: "Logitech MX Mechanical Mini for Mac",
    category: "Electronics",
    price: 149.99,
    originalPrice: null,
    rating: 4.0,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC_jeGOmRc4axL89RHDzqlzAlvFA-FzxgdTs7daBbgClKYgp8SRoJ6Ytz5m0wR45kd8lCmihnx1Oj0S_mk9svvht-3rLtqvu1CjghEFXQ84zN5hwjgPSbWJ7DBkqUnaLWkdxdJpBF-PRcqlbDFDTc5kRs6AHuxMP2SZCkrmLO97eVjAxlTSiyMneGzJqUQZN17p8m_J-A0-jSgj5tH4ZV4NQZ_BqsP7n4UdEu93LGZ4qFJ2g-sd-CWQ9zAPI0y50bAf-8MVDK8mHow",
    badge: "New",
    description: "Compact low-profile mechanical keyboard tailored for Mac workflows.",
    soldBy: "Tech Haven"
  },
  {
    id: 15,
    name: "Custom Artisan Purple Keycap Set (Keycaps Only)",
    category: "Accessories",
    price: 45.00,
    originalPrice: null,
    rating: 5.0,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBpHB1DKm4EQe1UlHCP7MtFsDEfnzo2xfmRNiYtJBHLAPx8ZDUjsUgiYhrJeDTH7tzU5yUCjPg6F2Lj1BCCgYeG1cYme00TwCZ0qtbfOSy-wgiWkhlD0ChTPIet-hBOSCCVznuzFpPQA4RUMITrn5ms9o-Z4B7SnTV6Hzt8t4mRS1iYC2ON2Eyxz3pw4lNkER9jzqXrUU950Ea_BEmEFGWqJBh-gxsioGn8qeRo-uDpr5i9oy8QITLkj38FqSQRQgbay9KvfaHxOaY",
    badge: null,
    description: "Artisan purple keycap set for custom mechanical keyboards.",
    soldBy: "Urban Threads"
  },
  {
    id: 16,
    name: "8BitDo Retro Mechanical Keyboard - N Edition",
    category: "Electronics",
    price: 99.99,
    originalPrice: null,
    rating: 4.5,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAr82UC0H8WtuxuzQcN2Pp15jnEYUW2_VEsGjgzUgw_6miJPpeGK_tr8hxJwg56k8Bp55LPiNrY0ZoeVeQQyrHAcYBMmzxiwbeeZLHs-ubHsIAn-7Akee4Vc1hsUfjClSUBthmkbF0xcPL5yXtt2dwA4NF-6spDLtMuIGIRrQpK_U2_5qfyOgcQ93_8_ea8mkv9SHfSa8ypWju1lkvSVMQBeiLycV9giiYak-KFi6ZggMb4y7zkpBbg2Q1X19U8l1IjIxHbSr-Jt_I",
    badge: "Best Seller",
    description: "Retro-inspired mechanical keyboard with modern wireless support.",
    soldBy: "Tech Haven"
  },
  {
    id: 17,
    name: "Corsair K70 RGB MK.2 Mechanical Gaming Keyboard",
    category: "Electronics",
    price: 159.99,
    originalPrice: null,
    rating: 5.0,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAP-xOp_KCexAGqVfoO6T2qVSa_bUYHDVGYOuSFm2yb0Qn2THawTb4z2sJMjSuDSGESEra5mEStbuxp5VTsjVz-CH3m_rAforqdL42YqKd9I3TFC1NPPa9inOdqFiLptGVu1qoLAf4JYm8mdu2xCoT-DjqLwPeie1_F_PG28YAWfSQMvWFTsdKB95vEgRjr0LxMG4CXox6bwmyR23aPpxEQDLD_Ad9NxdzTQ4oU-BxEkHOk_s8AuAyxYHjvLP0f2JE5Waul2TpIM8c",
    badge: null,
    description: "Full-size mechanical gaming keyboard with RGB lighting.",
    soldBy: "Tech Haven"
  },
  {
    id: 18,
    name: "Anne Pro 2 Mechanical Keyboard Wireless Bluetooth",
    category: "Electronics",
    price: 65.00,
    originalPrice: 89.00,
    rating: 4.0,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAo70EnPreGWczd2pumJl-sWCN718BotA55bJqrHop5SIOoje4O_lYmF7AmxeSLw-VraqgONDz6xc_VouMjhfkHTdyRZ92--XH-vUpRPhC4IQMeyQka526plvOeJsPlT3pkOR5IqF_XHgajHMD6HuDM86DblLFvyaVxuevrxzZh4jJlSsXmfSGEh027JyV0nfAsuhW5TwtVUEMCjEgu7AVxI1PnwYOgw16mMk71q4Tel_NDll5CENnHH1x47VngBB2uBiZ4jDGXbWM",
    badge: "Refurbished",
    description: "Compact 60% wireless mechanical keyboard with Bluetooth.",
    soldBy: "TechRefurb"
  },
  {
    id: 19,
    name: "Glorious Model O Wireless Gaming Mouse",
    category: "Electronics",
    price: 79.99,
    originalPrice: null,
    rating: 4.5,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuABQcTwQDhtR86xNbH2y27HUu5STKat1JdKaPtEFDjzAL6iJmjYBftEWdB6Ado1mQ-Bm0k7OMxI4oleqgl14zOilA4sKJl-DvFi_dU_AKjEQJvXFNaRcObOt9ZrYpOHyTGX15broD3iBhcCnr9lJvUbTFGpW9aRHHB1qk_JsSPbmvSFmBTsvdJQBRVKVkkq7FwZeOoghNhTIWi0dT3WIBJskJhLYJ0bkILPRLXmeIkZ54Ynl3eJLa1ydiYW06iurrFGPEUk45Ilhys",
    badge: null,
    description: "Ultra-lightweight wireless gaming mouse with honeycomb design.",
    soldBy: "Glorious"
  },
  {
    id: 20,
    name: "Pro Gamer Starter Pack: Keyboard + Mouse + Mat",
    category: "Electronics",
    price: 120.00,
    originalPrice: 150.00,
    rating: 4.0,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCoBbO2SQlb1BWmZ3gcAkKme2I83wt7D8_cGd1x7k6j50Mh-CLmy3o_Znkb-Y0lGSpoD-KHwbH4VUH5yzqrupbF1kaicbey197uLg-1ZcTw2wTd-WhM_WgXZkIB1B5mchJuOQPQFW53-ZruPTaGgWPWrilC0jCaXaf2ntQCaK8iX_HiswFRkcQw4rsG3hlvcst9kCbc-SzPjuFPKx_1BPG7ZZdIAtzHg2wAIhgltLu3tzZYrW6n-M7orWP9pqckj13ts6RqpbpZRRY",
    badge: "Bundle",
    description: "Starter bundle with keyboard, mouse, and desk mat.",
    soldBy: "GamerGear"
  },
  {
    id: 21,
    name: "Beats Studio Pro",
    category: "Electronics",
    price: 179.99,
    originalPrice: null,
    rating: 4.5,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqnAMT259nTw9WbZev67v4NtAKzlmGqPFt5FJb62QJEHnA9AFXVeeD6ytD44r-3g5xfDXRL1fRSc_psCmYh7n9-_nB9y4hpqVJMmTblDaJvmkOFqxp_Pv60zCiQtbWZvw2anbh1QsoMTCivSIO4XJQSybzb5tLm18Gmr18aGjVlSx2D53-9qBrDwxdP8wkdI7GhOxjA2mOhy2qjzpLmQ_mxwDN409gC9K3EsrFLwpc2LUrT-MgYB9ip6wVSysjwx6trlfXf6-DENA",
    badge: null,
    description: "Wireless noise cancelling headphones.",
    soldBy: "Tech Haven"
  },
  {
    id: 22,
    name: "Apple AirPods Max",
    category: "Electronics",
    price: 549.00,
    originalPrice: null,
    rating: 4.8,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCWacUatbIraa1pW6tgDmpkJFflMLkLMZd-xCyQzjnc1CghfvJqlPqqRJakHnEnTDDw-yZNXHjJjnYD3mFmRJGzatA_UbcxQrEp0Gg0vIHjmDrnJTeDxzXHFQb_OQBhkdaRaFvw80zKqMiX9uy2vl0up37dKH28GLxrBhTEhaT4ny-JkaSoRpTGgawbbi00BTrveun7EvubzWLXU83OyPmyCvH12uBFd-9Oufk1l38pmmeSB1Unh-ZUM-bsMnKvRboF8MlH-Ps5WTI",
    badge: null,
    description: "Over-ear headphones with premium audio.",
    soldBy: "Tech Haven"
  },
  {
    id: 23,
    name: "Bose QuietComfort 45",
    category: "Electronics",
    price: 329.00,
    originalPrice: null,
    rating: 4.7,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAym-AvkQfTKmkMr9laj6m3muaYBQfE2n5l0W4HLoGrZPXIE8amLmbsqcaZrLCjdGFAWKgpn3xnbMXUrJzlIZIBHmGUMP0Z95XkKCKu4swVf0n3wni6I1BHauhG1WxjEybcDGvjxY5oRkZWLFL9cweO-otcuuEGGrcodTPeS4O8VgWb8T3FdHNEmq67XgprUybqXGRFOAl6txl0JsRn30dqzJ0XVVPmkpqzCRR-sVeP-8IrfKkhr3fO0keOQmQlS-ya6nj7wbIMzd8",
    badge: null,
    description: "Bluetooth wireless noise cancelling headphones.",
    soldBy: "Tech Haven"
  },
  {
    id: 24,
    name: "Sennheiser Momentum 4",
    category: "Electronics",
    price: 299.95,
    originalPrice: null,
    rating: 4.6,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC6aBbXPxXJKsr0WKt3aEa5_1CwWG3XDHd4I75Sr2POQCM-SSEF-_h8OVZXKi6GEe9mukYhMOsqRPjC1cKhbco9w6fWIiWh-WahUiIxatceCnNin1pDiNvtS4LSMKAOOoeWvQfm5A6wteByclbR5VtD1_MIuCRW9eUji_pgdcBmu-Wjg6ynAXDfEpdoom0qPR-edTGi8AOQ-pA_MFDHYKz48KCfrhJPvIQ8Nm87eu4l46ettc7SJf0_fG_x0sYRQZwAzz07TlilLwc",
    badge: null,
    description: "Premium sound over-ear headphones.",
    soldBy: "Tech Haven"
  }
];

export default products;

// Helper to get product by slug
export const getProductBySlug = (slug) => products.find(p => p.slug === slug);
